name: Deploy Grocery Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t shafaque26/grocery-website:latest .
          docker push shafaque26/grocery-website:latest

      - name: Set up Kubernetes (Kind)
        uses: helm/kind-action@v1.8.0

      - name: Deploy to Kubernetes
        run: |
          kubectl cluster-info
          kubectl apply -f deployment.yaml
          kubectl get pods -A
